### ISSUE TITLE
你好，他报了这个错误是什么原因尼

### ISSUE THREAD

**Issue by zengAlex** [huangtengfei/apix#2]
![image](https://cloud.githubusercontent.com/assets/13888110/22876326/27b69164-f20b-11e6-8467-bdfa4cfa5eb5.png)
我的mongodb 版本是3.4.2

**Comment by huangtengfei** [comment]
@zengAlex  看一下下面这两个 issue

https://github.com/kissjs/node-mongoskin/issues/153

https://github.com/Automattic/monk/issues/91

应该是 monk 依赖的 mongoskin 版本有问题导致的，参照这个回答看能不能解决：

![image](https://cloud.githubusercontent.com/assets/3126745/22912028/e80efd6a-f29d-11e6-81c8-e59a587be511.png)

**Comment by zengAlex** [comment]
@huangtengfei 你好，我换了3个版本的mongoskin都不可以，分别是1.3.2 ,1.4.4,2.1.0

**Comment by zengAlex** [comment]
@huangtengfei  你好，原来需要把monk  的版本 也更新到最新版本

**Comment by zengAlex** [comment]
@huangtengfei 我在server.js 里面把监听的端口改成mongo 默认的271017 
![image](https://cloud.githubusercontent.com/assets/13888110/22917156/06c9ca62-f2be-11e6-8750-abd2b27f4a21.png)
